add new pr tests

diff --git a/.github/workflows/c-cpp.yml b/.github/workflows/c-cpp.yml
--- a/.github/workflows/c-cpp.yml
+++ b/.github/workflows/c-cpp.yml
@@ -1,23 +1,30 @@
 name: DevkitPPC Make
 
-on:
-  push:
-    branches: [ master ]
-  pull_request:
-    branches: [ master ]
+on: pull_request
 
 jobs:
   build:
-
     runs-on: ubuntu-latest
     container:
-      image: pheenoh/devkitppc-gcn:latest
-
+      image: ghcr.io/pheenoh/zsrtp-tpgz:latest
+      options: --shm-size=128m --ulimit core=-1 --privileged=true
     steps:
     - name: Checkout
       uses: actions/checkout@v1
       with:
         token: ${{secrets.MY_REPO_PAT}}
         submodules: recursive
+    - name: Debug Flag
+      run: export PR_TEST=1
     - name: Run Make
       run: make
+    - name: Move ISO
+      run: mv /gz2e01.iso ./GZ2E01.iso
+      # hacky work around to catch failures since romhack always returns 0 exit code
+    - name: Run Romhack
+      run: ROMHACK=$(romhack build --raw 2>&1) && ROMHACKSTRING=$(echo "$ROMHACK" | tail -c 9) && FINISHEDSTRING="Rom Hack" && echo "$ROMHACK" && if [ "$ROMHACKSTRING" != "$FINISHEDSTRING" ]; then exit 1; fi
+    - name: Boot Dolphin
+      run: |
+        dolphin-emu-nogui --platform=headless --video_backend=Null -e build/tpgz.iso &
+        sleep 15
+        /dme -c 0x80450580
