fix romhack build, update gitignore

diff --git a/.github/workflows/c-cpp.yml b/.github/workflows/c-cpp.yml
--- a/.github/workflows/c-cpp.yml
+++ b/.github/workflows/c-cpp.yml
@@ -21,5 +21,8 @@ jobs:
         submodules: recursive
     - name: Run Make
       run: make
+    - name: Move ISO
+      run: mv /gz2e01.iso ./gz2e01.iso
+      # hacky work around to catch failures since romhack always returns 0 exit code
     - name: Run Romhack
-      run: romhack build --raw
+      run: ROMHACK=$(romhack build --raw 2>&1) && ROMHACKSTRING=$(echo "$ROMHACK" | tail -c 9) && FINISHEDSTRING="Rom Hack" && echo "$ROMHACK" && if [ "$ROMHACKSTRING" != "$FINISHEDSTRING" ]; then exit 1; fi
